version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevent local node_modules from overwriting container’s
      - ./backend/config/.env.development:/app/config/.env.development
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped